### ISSUE TITLE
TriaxialHernquist Density

### ISSUE THREAD

**Issue by nstarman** [GalacticDynamics/galax#181]
There's something strange with the density. Who are we going to call? Maintainers!

Noticed in https://github.com/GalacticDynamics/galax/pull/179#issue-2165084330

The density is negative. That shouldn't happen.

**Comment by adrn** [comment]
Superseded by #194?

**Comment by adrn** [comment]
Oh this is not the feature request issue, just a thought... carry on!

**Comment by nstarman** [comment]
Diagnosed. Triaxiality in the potential!!
