### ISSUE TITLE
post galax install pip installations - breaks galax

### ISSUE THREAD

**Issue by dc-broo3** [GalacticDynamics/galax#487]
I've run into a bug whereby after I've installed galax and then install any further package that depends on numpy (I think?!) it breaks galax so I can no longer say "import galax.potential as gp" for example. 

I don't have a GitHub gist to show, but the error message complained about numpy having no 'typing' feature.

I can re-break another kernel if needed!

**Comment by nstarman** [comment]
> I can re-break another kernel if needed!

A MWE would definitely be appreciated!
It sounds like your numpy is being downgraded to a very old version.

**Comment by nstarman** [comment]
Was that right? is your `numpy` old?
